# Configuraci贸n del modelo LLM
llm:
  provider: mistral  # Opciones: mistral, openai
  models:
    mistral:
      name: mistral-small-2503
      api_key: o6MeatvTv1WsTlT6hG4Ld1soJbl8ppjk
      api_url: https://api.mistral.ai/v1/chat/completions
    openai:
      name: gpt-3.5-turbo
      api_key: ${OPENAI_API_KEY}
      api_url: https://api.openai.com/v1/chat/completions
  temperature: 0.7
  max_tokens: 1000

# Configuraci贸n de la interfaz
ui:
  theme: light
  language: es
  show_debug_info: false

# Configuraci贸n de datos
data:
  base_path: data
  file_types:
    - institutos.csv
    - colegios.csv
  required_columns:
    - codigo
    - nombre
    - localidad
    - municipio
    - provincia
    - direccion
    - codigo_postal

# Configuraci贸n de guardado
saved_configs:
  path: saved_configs
  format: yaml 