SUPABASE_URL = "https://dixeldbwutfhymkgfvaa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeGVsZGJ3dXRmaHlta2dmdmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTc5ODksImV4cCI6MjA3MzQzMzk4OX0.vkqEFWo5EagoSKND2u860JCV-Fb4LTL8LZhGKqX7CDs"
