# Streamlit Secrets Configuration
# Add your API keys here for deployment

# Mistral AI API Key (each user will input their own)
MISTRAL_API_KEY = "your-mistral-api-key-here"

# Supabase Configuration
SUPABASE_URL = "https://dixeldbwutfhymkgfvaa.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRpeGVsZGJ3dXRmaHlta2dmdmFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NTc5ODksImV4cCI6MjA3MzQzMzk4OX0.vkqEFWo5EagoSKND2u860JCV-Fb4LTL8LZhGKqX7CDs"

# Instructions:
# 1. Get your free Mistral API key from https://console.mistral.ai/
# 2. Get your Supabase URL and anon key from your Supabase project dashboard
# 3. Replace the placeholder values with your actual keys
# 4. In Streamlit Cloud, add these as secrets in your app settings
